"""Email and token

Revision ID: 09f4f9c2acf4
Revises: 9ee98fe5515f
Create Date: 2018-08-13 12:54:27.362172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f4f9c2acf4'
down_revision = '9ee98fe5515f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
