"""Shedule

Revision ID: 4715c225229c
Revises: 5131843a4f20
Create Date: 2018-08-28 15:25:16.566583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4715c225229c'
down_revision = '5131843a4f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shedules'))
    )
    op.create_table('shedule_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shedule_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shedule_id'], ['shedules.id'], name=op.f('fk_shedule_subject_shedule_id_shedules')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_shedule_subject_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shedule_subject'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.TEXT(), nullable=True))
    op.drop_table('shedule_subject')
    op.drop_table('shedules')
    # ### end Alembic commands ###
