"""Subjects

Revision ID: 5131843a4f20
Revises: d455a9b87b7d
Create Date: 2018-08-22 17:51:22.253069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5131843a4f20'
down_revision = 'd455a9b87b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.TEXT(), nullable=True))
    op.drop_table('subjects')
    # ### end Alembic commands ###
