"""Activated user

Revision ID: d455a9b87b7d
Revises: f6950c91b1dd
Create Date: 2018-08-13 16:36:37.161328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd455a9b87b7d'
down_revision = 'f6950c91b1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
