version: "3.3"
services:
  nginx:
    image: nginx
    volumes:
      - ..:/opt/eschool
      - ./config/nginx:/etc/nginx
    depends_on:
      - eschool
    networks:
      app_net:
        ipv4_address: 172.168.0.100
  eschool:
    build: ./.
    volumes:
      - ..:/opt/eschool
    tty: true
    networks:
      app_net:
        ipv4_address: 172.168.0.111

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 172.168.0.0/24
